server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index Stirps.html;

    location / {
        try_files $uri $uri/ /Stirps.html;
    }

    # Cache leve dos estáticos
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2?)$ {
        expires 1h;
        add_header Cache-Control "public";
    }
}
