// Família Bertolini-Albuquerque
// Generations: G1 (great-grandparents from Italy/Portugal), G2 (grandparents), G3 (parents), G4 (current user gen), G5 (children)

window.FAMILY = {
  rootUserId: "p_helena",
  people: {
    // ============ G1 — bisavós (1880s-1970s) ============
    p_giuseppe: {
      id: "p_giuseppe",
      first: "Giuseppe",
      last: "Bertolini",
      sex: "M",
      birth: { year: 1881, place: "Treviso, Itália" },
      death: { year: 1958, place: "São Paulo, SP" },
      occupation: "Marceneiro",
      photo: "olive",
      bio: "Imigrou para o Brasil em 1903 a bordo do navio Re Vittorio. Estabeleceu uma marcenaria no bairro do Brás que ainda existe na família.",
      tags: ["Imigrante", "Itália"],
      generation: 1,
    },
    p_assunta: {
      id: "p_assunta",
      first: "Assunta",
      last: "Lombardi",
      sex: "F",
      birth: { year: 1885, place: "Vicenza, Itália" },
      death: { year: 1971, place: "São Paulo, SP" },
      occupation: "Costureira",
      photo: "petrol",
      bio: "Conheceu Giuseppe a bordo do navio que os trouxe ao Brasil. Casaram em 1905 na Igreja da Achiropita.",
      tags: ["Imigrante", "Itália"],
      generation: 1,
    },
    p_joao: {
      id: "p_joao",
      first: "João Batista",
      last: "Albuquerque",
      sex: "M",
      birth: { year: 1878, place: "Évora, Portugal" },
      death: { year: 1949, place: "Recife, PE" },
      occupation: "Comerciante",
      photo: "beige",
      bio: "Veio de Portugal aos 19 anos. Foi um dos fundadores da Associação Comercial de Olinda.",
      tags: ["Imigrante", "Portugal"],
      generation: 1,
    },
    p_carmela: {
      id: "p_carmela",
      first: "Carmela",
      last: "Souza",
      sex: "F",
      birth: { year: 1884, place: "Olinda, PE" },
      death: { year: 1962, place: "Recife, PE" },
      occupation: "Professora",
      photo: "olive",
      bio: "Filha de senhor de engenho. Lecionou em escola pública por 38 anos.",
      tags: ["Brasil"],
      generation: 1,
    },

    // ============ G2 — avós (1910s-2000s) ============
    p_antonio: {
      id: "p_antonio",
      first: "Antônio",
      last: "Bertolini",
      sex: "M",
      birth: { year: 1912, place: "São Paulo, SP" },
      death: { year: 1989, place: "São Paulo, SP" },
      occupation: "Farmacêutico",
      photo: "petrol",
      parents: ["p_giuseppe", "p_assunta"],
      bio: "Primeiro da família a frequentar universidade. Formou-se na USP em 1936.",
      tags: ["Brasil", "Família paterna"],
      generation: 2,
    },
    p_isabel: {
      id: "p_isabel",
      first: "Isabel",
      last: "Albuquerque",
      sex: "F",
      birth: { year: 1918, place: "Recife, PE" },
      death: { year: 2003, place: "São Paulo, SP" },
      occupation: "Pianista",
      photo: "beige",
      parents: ["p_joao", "p_carmela"],
      bio: "Mudou-se para São Paulo aos 22 anos para estudar música. Conheceu Antônio em um concerto no Teatro Municipal.",
      tags: ["Família materna"],
      generation: 2,
    },

    // ============ G3 — pais e tios (1940s-) ============
    p_ricardo: {
      id: "p_ricardo",
      first: "Ricardo",
      last: "Bertolini Albuquerque",
      sex: "M",
      birth: { year: 1948, place: "São Paulo, SP" },
      death: null,
      occupation: "Arquiteto, aposentado",
      photo: "olive",
      parents: ["p_antonio", "p_isabel"],
      bio: "Formado pela FAU-USP. Projetou mais de 40 residências na grande São Paulo nas décadas de 70-90.",
      tags: ["Pai"],
      generation: 3,
    },
    p_clarice: {
      id: "p_clarice",
      first: "Clarice",
      last: "Moretti",
      sex: "F",
      birth: { year: 1951, place: "Caxias do Sul, RS" },
      death: null,
      occupation: "Médica pediatra",
      photo: "petrol",
      bio: "Conheceu Ricardo durante a faculdade. Mudou-se de Caxias do Sul para São Paulo em 1972.",
      tags: ["Mãe"],
      generation: 3,
    },
    p_marcos: {
      id: "p_marcos",
      first: "Marcos",
      last: "Bertolini Albuquerque",
      sex: "M",
      birth: { year: 1950, place: "São Paulo, SP" },
      death: null,
      occupation: "Advogado",
      photo: "beige",
      parents: ["p_antonio", "p_isabel"],
      bio: "Tio paterno. Vive em Florianópolis há 30 anos.",
      tags: ["Tio"],
      generation: 3,
    },
    p_lucia: {
      id: "p_lucia",
      first: "Lúcia",
      last: "Bertolini",
      sex: "F",
      birth: { year: 1955, place: "São Paulo, SP" },
      death: null,
      occupation: "Tradutora",
      photo: "olive",
      parents: ["p_antonio", "p_isabel"],
      bio: "Tia paterna. Mora em Lisboa desde 1992.",
      tags: ["Tia"],
      generation: 3,
    },

    // ============ G4 — Helena e primos (1970s-1990s) ============
    p_helena: {
      id: "p_helena",
      first: "Helena",
      last: "Bertolini Albuquerque",
      sex: "F",
      birth: { year: 1985, place: "São Paulo, SP" },
      death: null,
      occupation: "Designer de produto",
      photo: "petrol",
      parents: ["p_ricardo", "p_clarice"],
      bio: "Você. Iniciou a árvore genealógica em 2024 após encontrar uma caixa de fotos antigas no sótão da avó.",
      tags: ["Você"],
      generation: 4,
    },
    p_rafael: {
      id: "p_rafael",
      first: "Rafael",
      last: "Bertolini Albuquerque",
      sex: "M",
      birth: { year: 1982, place: "São Paulo, SP" },
      death: null,
      occupation: "Engenheiro civil",
      photo: "beige",
      parents: ["p_ricardo", "p_clarice"],
      bio: "Irmão mais velho. Vive em Curitiba com a esposa Mariana.",
      tags: ["Irmão"],
      generation: 4,
    },
    p_beatriz: {
      id: "p_beatriz",
      first: "Beatriz",
      last: "Bertolini Albuquerque",
      sex: "F",
      birth: { year: 1990, place: "São Paulo, SP" },
      death: null,
      occupation: "Veterinária",
      photo: "olive",
      parents: ["p_ricardo", "p_clarice"],
      bio: "Irmã caçula.",
      tags: ["Irmã"],
      generation: 4,
    },
    p_thiago: {
      id: "p_thiago",
      first: "Thiago",
      last: "Bertolini",
      sex: "M",
      birth: { year: 1980, place: "Florianópolis, SC" },
      death: null,
      occupation: "Surfista profissional",
      photo: "petrol",
      parents: ["p_marcos"],
      bio: "Primo. Filho do tio Marcos.",
      tags: ["Primo"],
      generation: 4,
    },

    // ============ Cônjuges ============
    p_diego: {
      id: "p_diego",
      first: "Diego",
      last: "Carvalho",
      sex: "M",
      birth: { year: 1983, place: "Rio de Janeiro, RJ" },
      death: null,
      occupation: "Roteirista",
      photo: "beige",
      bio: "Casado com Helena desde 2014.",
      tags: ["Cônjuge"],
      generation: 4,
    },
    p_mariana: {
      id: "p_mariana",
      first: "Mariana",
      last: "Pereira",
      sex: "F",
      birth: { year: 1984, place: "Curitiba, PR" },
      death: null,
      occupation: "Professora universitária",
      photo: "olive",
      bio: "Casada com Rafael desde 2011.",
      tags: ["Cunhada"],
      generation: 4,
    },

    // ============ G5 — filhos ============
    p_lorenzo: {
      id: "p_lorenzo",
      first: "Lorenzo",
      last: "Carvalho Bertolini",
      sex: "M",
      birth: { year: 2017, place: "São Paulo, SP" },
      death: null,
      occupation: "Estudante",
      photo: "olive",
      parents: ["p_helena", "p_diego"],
      bio: "Filho de Helena e Diego.",
      tags: ["Filho"],
      generation: 5,
    },
    p_alice: {
      id: "p_alice",
      first: "Alice",
      last: "Carvalho Bertolini",
      sex: "F",
      birth: { year: 2020, place: "São Paulo, SP" },
      death: null,
      occupation: "Estudante",
      photo: "petrol",
      parents: ["p_helena", "p_diego"],
      bio: "Filha de Helena e Diego.",
      tags: ["Filha"],
      generation: 5,
    },
    p_pedro: {
      id: "p_pedro",
      first: "Pedro",
      last: "Pereira Bertolini",
      sex: "M",
      birth: { year: 2014, place: "Curitiba, PR" },
      death: null,
      occupation: "Estudante",
      photo: "beige",
      parents: ["p_rafael", "p_mariana"],
      bio: "Sobrinho.",
      tags: ["Sobrinho"],
      generation: 5,
    },
  },

  // Marriages / unions
  unions: [
    { partners: ["p_giuseppe", "p_assunta"], year: 1905, place: "Igreja da Achiropita, SP" },
    { partners: ["p_joao", "p_carmela"], year: 1908, place: "Olinda, PE" },
    { partners: ["p_antonio", "p_isabel"], year: 1944, place: "São Paulo, SP" },
    { partners: ["p_ricardo", "p_clarice"], year: 1976, place: "São Paulo, SP" },
    { partners: ["p_helena", "p_diego"], year: 2014, place: "São Paulo, SP" },
    { partners: ["p_rafael", "p_mariana"], year: 2011, place: "Curitiba, PR" },
  ],

  // Recent activity feed
  activity: [
    { id: "a1", type: "added", who: "p_giuseppe", when: "há 2 dias", actor: "Você" },
    { id: "a2", type: "photo", who: "p_isabel", when: "há 4 dias", actor: "Você", note: "12 fotos digitalizadas" },
    { id: "a3", type: "document", who: "p_giuseppe", when: "há 1 semana", actor: "Você", note: "Certidão de chegada — Hospedaria de Imigrantes" },
    { id: "a4", type: "match", who: "p_assunta", when: "há 1 semana", note: "3 registros encontrados em arquivos italianos" },
    { id: "a5", type: "added", who: "p_carmela", when: "há 2 semanas", actor: "Tia Lúcia" },
    { id: "a6", type: "edited", who: "p_antonio", when: "há 3 semanas", actor: "Você", note: "Biografia atualizada" },
  ],

  // Suggested connections
  suggestions: [
    { id: "s1", title: "Possível irmão de Giuseppe", subtitle: "Pietro Bertolini, nascido em 1879 em Treviso", confidence: 92, source: "Archivio di Stato di Treviso" },
    { id: "s2", title: "Registro de batismo encontrado", subtitle: "Carmela Souza — Igreja da Sé, Olinda, 1884", confidence: 88, source: "FamilySearch" },
    { id: "s3", title: "Possível prima distante", subtitle: "Ana Bertolini Costa em São Paulo", confidence: 71, source: "Conexão Stirps" },
  ],

  // Timeline events
  timeline: [
    { year: 1881, label: "Nascimento de Giuseppe Bertolini", place: "Treviso, IT" },
    { year: 1903, label: "Imigração para o Brasil", place: "Porto de Santos" },
    { year: 1905, label: "Casamento Giuseppe & Assunta", place: "São Paulo" },
    { year: 1912, label: "Nascimento de Antônio", place: "São Paulo" },
    { year: 1936, label: "Antônio se forma na USP", place: "São Paulo" },
    { year: 1944, label: "Casamento Antônio & Isabel", place: "São Paulo" },
    { year: 1985, label: "Nascimento de Helena", place: "São Paulo" },
    { year: 2014, label: "Casamento Helena & Diego", place: "São Paulo" },
  ],
};
